version: "3.3"

networks:
  timetracker:
    driver: bridge
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timetracker
    ports:
      - 3306:3306
    networks:
      - timetracker
    volumes:
      - ./mysql:/var/lib/mysql
  timetracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timetracker
    restart: always
    depends_on:
      - mysql
    ports:
      - 3000:3000
    networks:
      - timetracker
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/timetracker
